### ISSUE TITLE
es6 source

### ISSUE THREAD

**Issue by ekoeryanto** [ariya/unmix#3]
### Steps to reproduce
just navigate to https://github.com/ariya/unmix/blob/master/src/unmix.js

### Expected output
clean code so people can contribute with happy

### Actual output
hardcoded umd file

### Additional references
Mungkin saya akan coba buat PR pake rollup jika disetujui.

**Comment by ariya** [comment]
The source file is too small to worry about build step. The UMD stuff is just a dozen of (harmless) lines. Maybe once it gets bigger then we shall revisit the issue.

Thank you!
